adapters:
  tapjoy:
    enabled: true
  rubicon:
    enabled: true
    XAPI.Username: user1
    XAPI.Password: password1
metrics:
  prefix: prebid
cache:
  scheme: http
  host: localhost
  path: /cache
  query: uuid=%PBS_CACHE_UUID%
settings:
  filesystem:
    settings-filename: sample-app-settings.yml
    stored-requests-dir: /tmp
    stored-imps-dir: /tmp
gdpr:
  vendorlist:
    filesystem-cache-dir: /tmp
status-response: "ok"